from EvolutionaryComputation.AutoML.modules import CustomConvolutionModule, CustomDeepModule, Saved_Weights, \
    hyper_param_sample
from EvolutionaryComputation.AutoML.initial_populations import NetworkInitialPopulation
from EvolutionaryComputation.AutoML.neural_network_architecture import NetworkArchitectureEvolution
from EvolutionaryComputation.AutoML.initial_populations import CustomInitialPopulation
from EvolutionaryComputation.AutoML.custom_automl_algorithm import CustomAutoMLAlgorithm
